/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectoop;

/**
 *
 * @author thinh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocation(300, 100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        tuLanhPn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mayLanhPn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mayGiatPn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mayNuocNongPn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dienGiaDungPn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dienThoaiPn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        laptopPn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        loaPn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        menuScrPanel = new javax.swing.JScrollPane();
        menuPanel = new javax.swing.JPanel();
        tvRb = new javax.swing.JRadioButton();
        tuLanhRb = new javax.swing.JRadioButton();
        mayLanhRb = new javax.swing.JRadioButton();
        mayGiatRb = new javax.swing.JRadioButton();
        mayNuocNongRb = new javax.swing.JRadioButton();
        dienGiaDungRb = new javax.swing.JRadioButton();
        laptopRb = new javax.swing.JRadioButton();
        dienThoaiRb = new javax.swing.JRadioButton();
        loaRb = new javax.swing.JRadioButton();
        showItemScrPanel = new javax.swing.JScrollPane();
        tvPanel = new javax.swing.JPanel();
        itemPn1 = new com.mycompany.projectoop.panel.itemPn();
        itemPn2 = new com.mycompany.projectoop.panel.itemPn();
        itemPn3 = new com.mycompany.projectoop.panel.itemPn();
        itemPn4 = new com.mycompany.projectoop.panel.itemPn();
        itemPn6 = new com.mycompany.projectoop.panel.itemPn();
        itemPn7 = new com.mycompany.projectoop.panel.itemPn();
        itemPn8 = new com.mycompany.projectoop.panel.itemPn();
        itemPn9 = new com.mycompany.projectoop.panel.itemPn();
        itemPn10 = new com.mycompany.projectoop.panel.itemPn();
        itemPn11 = new com.mycompany.projectoop.panel.itemPn();
        itemPn13 = new com.mycompany.projectoop.panel.itemPn();
        itemPn14 = new com.mycompany.projectoop.panel.itemPn();
        itemPn15 = new com.mycompany.projectoop.panel.itemPn();
        itemPn16 = new com.mycompany.projectoop.panel.itemPn();
        itemPn17 = new com.mycompany.projectoop.panel.itemPn();
        itemPn18 = new com.mycompany.projectoop.panel.itemPn();

        jLabel1.setText("tu lanh");

        javax.swing.GroupLayout tuLanhPnLayout = new javax.swing.GroupLayout(tuLanhPn);
        tuLanhPn.setLayout(tuLanhPnLayout);
        tuLanhPnLayout.setHorizontalGroup(
            tuLanhPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuLanhPnLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        tuLanhPnLayout.setVerticalGroup(
            tuLanhPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tuLanhPnLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jLabel2.setText("maylanh");

        javax.swing.GroupLayout mayLanhPnLayout = new javax.swing.GroupLayout(mayLanhPn);
        mayLanhPn.setLayout(mayLanhPnLayout);
        mayLanhPnLayout.setHorizontalGroup(
            mayLanhPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mayLanhPnLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        mayLanhPnLayout.setVerticalGroup(
            mayLanhPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mayLanhPnLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jLabel3.setText("maygiat");

        javax.swing.GroupLayout mayGiatPnLayout = new javax.swing.GroupLayout(mayGiatPn);
        mayGiatPn.setLayout(mayGiatPnLayout);
        mayGiatPnLayout.setHorizontalGroup(
            mayGiatPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mayGiatPnLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        mayGiatPnLayout.setVerticalGroup(
            mayGiatPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mayGiatPnLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel3)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jLabel4.setText("maynuocnogn");

        javax.swing.GroupLayout mayNuocNongPnLayout = new javax.swing.GroupLayout(mayNuocNongPn);
        mayNuocNongPn.setLayout(mayNuocNongPnLayout);
        mayNuocNongPnLayout.setHorizontalGroup(
            mayNuocNongPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mayNuocNongPnLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mayNuocNongPnLayout.setVerticalGroup(
            mayNuocNongPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mayNuocNongPnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel5.setText("diengiadung");

        javax.swing.GroupLayout dienGiaDungPnLayout = new javax.swing.GroupLayout(dienGiaDungPn);
        dienGiaDungPn.setLayout(dienGiaDungPnLayout);
        dienGiaDungPnLayout.setHorizontalGroup(
            dienGiaDungPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dienGiaDungPnLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );
        dienGiaDungPnLayout.setVerticalGroup(
            dienGiaDungPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dienGiaDungPnLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel6.setText("dienthoai");

        javax.swing.GroupLayout dienThoaiPnLayout = new javax.swing.GroupLayout(dienThoaiPn);
        dienThoaiPn.setLayout(dienThoaiPnLayout);
        dienThoaiPnLayout.setHorizontalGroup(
            dienThoaiPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dienThoaiPnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        dienThoaiPnLayout.setVerticalGroup(
            dienThoaiPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dienThoaiPnLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(36, 36, 36))
        );

        jLabel7.setText("laptop");

        javax.swing.GroupLayout laptopPnLayout = new javax.swing.GroupLayout(laptopPn);
        laptopPn.setLayout(laptopPnLayout);
        laptopPnLayout.setHorizontalGroup(
            laptopPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laptopPnLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18))
        );
        laptopPnLayout.setVerticalGroup(
            laptopPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laptopPnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel8.setText("loa");

        javax.swing.GroupLayout loaPnLayout = new javax.swing.GroupLayout(loaPn);
        loaPn.setLayout(loaPnLayout);
        loaPnLayout.setHorizontalGroup(
            loaPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loaPnLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(28, 28, 28))
        );
        loaPnLayout.setVerticalGroup(
            loaPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loaPnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        buttonGroup.add(tvRb);
        tvRb.setText("TV");
        tvRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvRbActionPerformed(evt);
            }
        });

        buttonGroup.add(tuLanhRb);
        tuLanhRb.setText("Tủ Lạnh");
        tuLanhRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuLanhRbActionPerformed(evt);
            }
        });

        buttonGroup.add(mayLanhRb);
        mayLanhRb.setText("Máy Lạnh");
        mayLanhRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayLanhRbActionPerformed(evt);
            }
        });

        buttonGroup.add(mayGiatRb);
        mayGiatRb.setText("Máy giặt");
        mayGiatRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayGiatRbActionPerformed(evt);
            }
        });

        buttonGroup.add(mayNuocNongRb);
        mayNuocNongRb.setText("Máy nước nóng");
        mayNuocNongRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayNuocNongRbActionPerformed(evt);
            }
        });

        buttonGroup.add(dienGiaDungRb);
        dienGiaDungRb.setText("Điện gia dụng");
        dienGiaDungRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dienGiaDungRbActionPerformed(evt);
            }
        });

        buttonGroup.add(laptopRb);
        laptopRb.setText("Laptop");
        laptopRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopRbActionPerformed(evt);
            }
        });

        buttonGroup.add(dienThoaiRb);
        dienThoaiRb.setText("Điện thoại");
        dienThoaiRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dienThoaiRbActionPerformed(evt);
            }
        });

        buttonGroup.add(loaRb);
        loaRb.setText("Loa");
        loaRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(tvRb)
                .addGap(20, 20, 20)
                .addComponent(tuLanhRb)
                .addGap(20, 20, 20)
                .addComponent(mayLanhRb)
                .addGap(20, 20, 20)
                .addComponent(mayGiatRb)
                .addGap(20, 20, 20)
                .addComponent(mayNuocNongRb)
                .addGap(20, 20, 20)
                .addComponent(dienGiaDungRb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(laptopRb)
                .addGap(20, 20, 20)
                .addComponent(dienThoaiRb)
                .addGap(20, 20, 20)
                .addComponent(loaRb, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tvRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tuLanhRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mayLanhRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mayGiatRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mayNuocNongRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dienGiaDungRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dienThoaiRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(laptopRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(loaRb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuScrPanel.setViewportView(menuPanel);

        javax.swing.GroupLayout tvPanelLayout = new javax.swing.GroupLayout(tvPanel);
        tvPanel.setLayout(tvPanelLayout);
        tvPanelLayout.setHorizontalGroup(
            tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tvPanelLayout.createSequentialGroup()
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemPn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(itemPn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemPn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tvPanelLayout.createSequentialGroup()
                                .addComponent(itemPn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemPn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tvPanelLayout.createSequentialGroup()
                                .addComponent(itemPn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemPn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addComponent(itemPn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemPn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemPn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addComponent(itemPn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemPn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemPn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        tvPanelLayout.setVerticalGroup(
            tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tvPanelLayout.createSequentialGroup()
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemPn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemPn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemPn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemPn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemPn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemPn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemPn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPn18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        showItemScrPanel.setViewportView(tvPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuScrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(showItemScrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuScrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(showItemScrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tvRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvRbActionPerformed
        // TODO add your handling code here:
        if(tvRb.isSelected()){
            showItemScrPanel.setViewportView(tvPanel);
        }
        
        
    }//GEN-LAST:event_tvRbActionPerformed

    private void mayLanhRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayLanhRbActionPerformed
        // TODO add your handling code here:
        if(mayLanhRb.isSelected()){
            showItemScrPanel.setViewportView(mayLanhPn);
        }
    }//GEN-LAST:event_mayLanhRbActionPerformed

    private void mayGiatRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayGiatRbActionPerformed
        // TODO add your handling code here:
        if(mayGiatRb.isSelected()){
            showItemScrPanel.setViewportView(mayGiatPn);
        }
    }//GEN-LAST:event_mayGiatRbActionPerformed

    private void loaRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaRbActionPerformed
        // TODO add your handling code here:
        if(loaRb.isSelected()){
            showItemScrPanel.setViewportView(loaPn);
        }
    }//GEN-LAST:event_loaRbActionPerformed

    private void tuLanhRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuLanhRbActionPerformed
        // TODO add your handling code here:
        if(tuLanhRb.isSelected()){
            showItemScrPanel.setViewportView(tuLanhPn);
        }
    }//GEN-LAST:event_tuLanhRbActionPerformed

    private void mayNuocNongRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayNuocNongRbActionPerformed
        // TODO add your handling code here:
        if(mayNuocNongRb.isSelected()){
            showItemScrPanel.setViewportView(mayNuocNongPn);
        }
    }//GEN-LAST:event_mayNuocNongRbActionPerformed

    private void dienGiaDungRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dienGiaDungRbActionPerformed
        // TODO add your handling code here:
        if(dienGiaDungRb.isSelected()){
            showItemScrPanel.setViewportView(dienGiaDungPn);
        }
    }//GEN-LAST:event_dienGiaDungRbActionPerformed

    private void laptopRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopRbActionPerformed
        // TODO add your handling code here:
        if(laptopRb.isSelected()){
            showItemScrPanel.setViewportView(laptopPn);
        }
    }//GEN-LAST:event_laptopRbActionPerformed

    private void dienThoaiRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dienThoaiRbActionPerformed
        // TODO add your handling code here:
        if(dienThoaiRb.isSelected()){
            showItemScrPanel.setViewportView(dienThoaiPn);
        }
    }//GEN-LAST:event_dienThoaiRbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel dienGiaDungPn;
    private javax.swing.JRadioButton dienGiaDungRb;
    private javax.swing.JPanel dienThoaiPn;
    private javax.swing.JRadioButton dienThoaiRb;
    private com.mycompany.projectoop.panel.itemPn itemPn1;
    private com.mycompany.projectoop.panel.itemPn itemPn10;
    private com.mycompany.projectoop.panel.itemPn itemPn11;
    private com.mycompany.projectoop.panel.itemPn itemPn13;
    private com.mycompany.projectoop.panel.itemPn itemPn14;
    private com.mycompany.projectoop.panel.itemPn itemPn15;
    private com.mycompany.projectoop.panel.itemPn itemPn16;
    private com.mycompany.projectoop.panel.itemPn itemPn17;
    private com.mycompany.projectoop.panel.itemPn itemPn18;
    private com.mycompany.projectoop.panel.itemPn itemPn2;
    private com.mycompany.projectoop.panel.itemPn itemPn3;
    private com.mycompany.projectoop.panel.itemPn itemPn4;
    private com.mycompany.projectoop.panel.itemPn itemPn6;
    private com.mycompany.projectoop.panel.itemPn itemPn7;
    private com.mycompany.projectoop.panel.itemPn itemPn8;
    private com.mycompany.projectoop.panel.itemPn itemPn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel laptopPn;
    private javax.swing.JRadioButton laptopRb;
    private javax.swing.JPanel loaPn;
    private javax.swing.JRadioButton loaRb;
    private javax.swing.JPanel mayGiatPn;
    private javax.swing.JRadioButton mayGiatRb;
    private javax.swing.JPanel mayLanhPn;
    private javax.swing.JRadioButton mayLanhRb;
    private javax.swing.JPanel mayNuocNongPn;
    private javax.swing.JRadioButton mayNuocNongRb;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JScrollPane menuScrPanel;
    private javax.swing.JScrollPane showItemScrPanel;
    private javax.swing.JPanel tuLanhPn;
    private javax.swing.JRadioButton tuLanhRb;
    private javax.swing.JPanel tvPanel;
    private javax.swing.JRadioButton tvRb;
    // End of variables declaration//GEN-END:variables
}
